### ISSUE TITLE
open manipulator pro latest version error

### ISSUE THREAD

**Issue by YDK18** [ROBOTIS-GIT/open_manipulator_p#30] opened 2019-12-09 06:12 UTC
I download the latest version in master at https://github.com/ROBOTIS-GIT/open_manipulator_pro.git.
We use ubuntu 16.04. LTS. ROS: kinetic
Do you mean the version with kinetic-devel branch? But I also test the kinetic version, it doesn't work either.
I was trying to test the lastest version. Arm works well in y direction and z direction. When arm reached the limitation of the physical size, terminator gave error messages and stop. However the arm still works strange in x direction. Arm moved with a not understandable behavior.
As shown in the first picture, a strange posture was output.

![70015595-36c56900-15c1-11ea-9792-bd2baf9de98b](https://user-images.githubusercontent.com/38091018/70411549-e43eed80-1a95-11ea-93df-6c30ea499295.jpg)

![70015879-14801b00-15c2-11ea-9465-bff8de859509](https://user-images.githubusercontent.com/38091018/70411560-ee60ec00-1a95-11ea-9368-7b3c62b6edfe.png)
![70015880-1518b180-15c2-11ea-8083-52b7ac4dfae4](https://user-images.githubusercontent.com/38091018/70411565-f4ef6380-1a95-11ea-9c77-63e5c733e3ca.png)

**Comment by JaehyunShim** [comment] 2019-12-09 08:45
duplicate of [the issue](https://github.com/ROBOTIS-GIT/open_manipulator_pro/issues/27)

**Closed as completed by JaehyunShim** 2019-12-09 08:45 UTC
