### ISSUE TITLE
Problem with open_manipulator_pro_teleop not yet finished!

### ISSUE THREAD

**Issue by YDK18** [ROBOTIS-GIT/open_manipulator_p#33] opened 2020-01-07 07:08 UTC
Hello. I was trying to test the lastest version.
Arm works well in y direction and z direction. When arm reached the limitation of the physical size, terminator gave error messages and stop. However the arm still works strange in x direction. Arm moved with a not understandable behavior.

In addition, we previously posted a new issue that you closed before unresolved.
Don't end the unresolved issue, just add a new comment here.

**Comment by JaehyunShim** [comment] 2020-01-08 04:57
duplicate of [the issue](https://github.com/ROBOTIS-GIT/open_manipulator_pro/issues/27)

**Closed as completed by JaehyunShim** 2020-01-08 04:57 UTC
